export const formCodes = {
    formValidationFailed: "validation-failed",
    formFieldTypes: {
        missing: "missing",
        overflow: "overflow",
        underflow: "underflow",
        length: "length",
        invalid: "invalid",
        unknown: "unknown",
    },
    formFieldInvalidTypeCauses: {
        invalidValue: "invalid-value",
        invalidEnumValue: "invalid-enum-value",
        requireHttps: "require-https",
        missingHost: "missing-host",
        containsPath: "contains-path",
        containsQuery: "contains-query",
        containsFragment: "contains-fragment",
        absoluteUrl: "absolute-url",
        nilId: "nil-id",
        invalidEmail: "invalid-email",
        missingMxRecords: "missing-mx-records",
        notDigit: "not-digit",
        notBase64UrlEncoded: "not-base64-url-encoded",
        invalidUrl: "invalid-url",
        nullValue: "null-value",
    },
} as const;
